### ISSUE TITLE
Error: Cannot find module 'XMLHttpRequest

### ISSUE THREAD

**Issue by iamlukesky** [gee-community/ee-runner#11]
I get this both when I do the 'use as package' and 'use as CLI tool' option.

```
$ node ee-runner.js examples/hello.js 
module.js:472
    throw err;
    ^

Error: Cannot find module 'XMLHttpRequest'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> ([ ... ]/ee-runner/index.js:16:25)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

```
$ node --version
v7.10.1
```

**Comment by gena** [comment]
Do you have all dependent packages? 

Any error after:
```npm run init```
?

**Comment by matthiasdemuzere** [comment]
I actually get the same error as above.

`node ee-runner.js examples/hello.js
module.js:471
    throw err;
    ^

Error: Cannot find module 'XMLHttpRequest'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/maffie/scripts/gee/ee-runner/index.js:16:25)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
`

And I do not get an error after npm run int. 
I installed xmlhttprequest separately, but with/without -g option. Did init again, but I still get the same error.

Any ideas?

**Comment by iamlukesky** [comment]
@gena no, no errors after `npm run init`

**Comment by gena** [comment]
Can you try it once again?

**Comment by iamlukesky** [comment]
Great, https://github.com/gee-community/ee-runner/commit/690d11c3fbe78305458f3ecf410ccd7f6dc47dfd seems to have done the trick!
