### ISSUE TITLE
Error: cache.get is not a function

### ISSUE THREAD

**Issue by giswqs** [gee-community/ee-runner#22]
@gena I have installed ee-runner using `npm install -g ee-runner`. However, when I tried to run the example using `node ee-runner.js examples/hello.js`, I got the following errors. Any help will be appreciated!

```
internal/modules/cjs/loader.js:87
    const result = cache.get(filename);
                         ^

TypeError: cache.get is not a function
    at stat (internal/modules/cjs/loader.js:87:26)
    at Function.Module._findPath (internal/modules/cjs/loader.js:244:20)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:578:25)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/media/hdd/Dropbox/git/earth-engine/ee-runner/authenticate.js:4:14)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)

```

**Comment by gena** [comment]
Which Node.js version? I've just tested locally with v9.10.1, seems to work.

**Comment by giswqs** [comment]
I am using Manjaro Linux KDE Edition 17.1.12 with [Node.js v10.10.0](https://nodejs.org/en/blog/release/v10.10.0/)

**Comment by giswqs** [comment]
@gena I still could not get ee-runner to work on Manjaro Linux with Node.js v10.10.0 due to the `TypeError: cache.get is not a function.` Therefore, I tried Ubuntu Linux with Node.js v8.10.0. and npm v3.5.2. And I am happy to report that it works like a charm in Ubuntu. Many thanks for developing such a great package!

**Comment by gena** [comment]
It feels like some bug with Node 10.10.0 or your installation. Will see if I can reproduce it.

**Comment by gena** [comment]
Should work fine in v10.x as well. It was a bug related to global variables.

**Comment by giswqs** [comment]
It works now. Thanks a lot for the fix!
