### ISSUE TITLE
Error: spawn E2BIG

### ISSUE THREAD

**Issue by giswqs** [gee-community/ee-runner#25]
I encountered a `spawn E2BIG` error when trying to use ee-runner to export a CSV file. See the error message below. I found a similar error message reported [HERE](https://medium.com/@tudip/post-large-json-data-without-curl-call-in-node-js-a5c1dc5dfa02). Not sure if this issue is caused by ee-runner or the earthengine api. Any help will be appreciated!

```
[user@linux]$ ee-runner huc.js 
Running script: huc.js
internal/child_process.js:371
    throw errnoException(err, 'spawn');
    ^

Error: spawn E2BIG
    at ChildProcess.spawn (internal/child_process.js:371:11)
    at spawn (child_process.js:561:9)
    at exports.XMLHttpRequest.send (/usr/lib/node_modules/ee-runner/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:503:22)
    at Object.ee.data.send_ (/usr/lib/node_modules/ee-runner/node_modules/@google/earthengine/build/main.js:14992:13)
    at Object.ee.data.startProcessing (/usr/lib/node_modules/ee-runner/node_modules/@google/earthengine/build/main.js:14638:18)
    at Object.<anonymous> (/media/hdd/Dropbox/git/earth-engine/ee-runner/examples/huc.js:535:9)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
```
Sample GEE code:
```
var csv_feat_col = ee.FeatureCollection([csv_feature]);

var json = ee.Serializer.toJSON(csv_feat_col);
var desc = 'HUC_' + huc10_id + '_Stats';

var params = {
    json: json,
    type: 'EXPORT_FEATURES',
    description: desc,
    folder: 'GEE',
    fileFormat: 'CSV'
};

var taskId = ee.data.newTaskId(1);
ee.data.startProcessing(taskId, params);
```

**Comment by giswqs** [comment]
Here is the [link](https://drive.google.com/file/d/1GF6GedbD8_0lHCI9B_7Czd1JDTOdvHsV/view) to the json file exported from the `ee.Serializer.toJSON` function. The file size is 78 KB. Could this be reason for the `spawn E2BIG` error?

**Comment by MarcYin** [comment]
Got the same error:

```javascript
internal/child_process.js:371
    throw errnoException(err, 'spawn');
    ^

Error: spawn E2BIG
    at ChildProcess.spawn (internal/child_process.js:371:11)
    at spawn (child_process.js:561:9)
    at exports.XMLHttpRequest.send (/home/ucfafyi/ee-runner/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:503:22)
    at Object.ee.data.send_ (/home/ucfafyi/ee-runner/node_modules/@google/earthengine/build/main.js:15363:13)
    at Object.ee.data.computeValue (/home/ucfafyi/ee-runner/node_modules/@google/earthengine/build/main.js:14703:18)
    at ee.Geometry.ee.ComputedObject.getInfo (/home/ucfafyi/ee-runner/node_modules/@google/earthengine/build/main.js:15622:18)
    at Object.<anonymous> (/home/ucfafyi/ee-runner/SIAC/AC_processor:251:65)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
```

**Comment by gena** [comment]
This kind of errors usually come from using the sync API, try providing a callback instead. 

I cannot reproduce it either, please attach a working (crashing) example.

**Comment by MarcYin** [comment]
Hi,

The code I have used to test is here: 

https://github.com/MarcYin/TEST_SIAC

And the way I run the code is:

`node ee-runner/ee-runner.js SIAC/AC_processor.js`

The working version on code editor is here:

https://code.earthengine.google.com/b4fb38865be2bfb59f04b93eb415a042

Thank you very much,

Marc.

**Comment by gena** [comment]
The problem comes with xmlhttprequest, try running async, this is not ideal, but you should not get that error anymore:

```javascript
var taskId = ee.data.newTaskId(1)

let deasync = require('deasync')

let done = false

ee.data.startProcessing(taskId, params, () => { done = true })

while(!done) {
  deasync.sleep(100)
}


```

This will make sure that the startProcessing runs asynchronously, and once done - the Node.js process will exit

**Comment by MarcYin** [comment]
Hi,

It dose the magic to solve the problem, thank you very much! 

BTW, is it going to be implemented as a option for those codes (like mine...) as a trial and error process?

Marc.
