### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by angel-r** [gee-community/ee-runner#28]
after execute the next command 

` ee-runner caminos.js`

I receive this error

  ```
  var client = new google.auth.OAuth2(o.client_id, o.client_secret, o.redirect_uri);
                                 ^

TypeError: Cannot read property 'OAuth2' of undefined
    at Object.initialize (C:\Users\angel\AppData\Roaming\npm\node_modules\ee-runner\authenticate.js:21:34)
    at Object.<anonymous> (C:\Users\angel\AppData\Roaming\npm\node_modules\ee-runner\ee-runner.js:26:5)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
```

**Comment by gena** [comment]
Sorry for the delay, this is fixed in a new version, please update to v0.0.31
